language: python
python:
  - 2.6
  - 2.7
install: python setup.py install
before_script: pip install -r requirements-test.txt
script:
  - py.test
  - python test_requests.py
  - python test_sqlalchemy.py
  - python test_urllib2.py
